### ISSUE TITLE
how to needed

### ISSUE THREAD

**Issue by enlight3d** [clementguillot/nx-cloud-ce#201]
Hello, I've discovered your project and decided to give it a go for my organization !
I've managed to install your helm chart on my build kubernetes server (had to provide a configmap for the S3 to the server app as it seems that providing `minio: true` in the values did not do anything). Maybe the helm chart that is currently online isn't the latest ?
Also, you should consider to have an ingress part of your templates in the helm chart.

Any way, I managed to have it running and be exposed to the web. I've connected it using `NX_CLOUD_API="https://nx-cloud-ce.domain.com" npx nx connect`.

My issue is that now, I see errors about NX Cloud while building something locally on my computer... For example see attached image

![image](https://github.com/user-attachments/assets/1130b7b9-e5bd-43d9-b4ca-0494627527c3)

Could you help me ? There are not many logs on the server app :
```
2024-10-17T08:34:06.329308726Z 2024-10-17 08:34:06,204 INFO  [org.nxc.ser.tec.fil.GlobalErrorFilter] (vert.x-eventloop-thread-3) Error code 403 at http://server/nx-cloud/runs/end - null
2024-10-17T08:34:31.417632461Z 2024-10-17 08:34:31,292 INFO  [org.nxc.ser.tec.fil.GlobalErrorFilter] (vert.x-eventloop-thread-2) Error code 403 at http://server/nx-cloud/v2/runs/start - null
2024-10-17 08:35:08,576 INFO  [org.nxc.ser.tec.fil.GlobalErrorFilter] (vert.x-eventloop-thread-0) Error code 403 at http://server/nx-cloud/runs/end - null
```

**Comment by clementguillot** [comment]
Hi @enlight3d 

Adding an ingress to the template is definitely something that should be added to the backlog. However, our instance of Nx Cloud CE is behind an Istio gateway and we don’t use Kube’s Ingress API, so, it won't be the higher priority for now.

Regarding your setup, your screenshot suggests a 500 error from backend, and your logs a 403 error. Strange.

What version of Nx are you using?

I have not updated the `nx-cloud-client-bundle` for a while. Maybe you can retry your failing command after a `nx reset`? (or you can try to remove `.nx` folder at root of your workdir). To ensure that your Nx CLI downloads the same version of the daemon as actually supported by the backend.

**Comment by enlight3d** [comment]
I you prefer, we can talk on discord or anything else ?
I'm currently even trying to run your server locally and it seems to work !

**Comment by clementguillot** [comment]
Sure, you can reach my on Discord at "nhx69"

**Comment by clementguillot** [comment]
@enlight3d I hope your issue is solved for now. Feel free to reopen/open new issue if you need further help.
