### ISSUE TITLE
Support GCS as storage backend

### ISSUE THREAD

**Issue by clementguillot** [clementguillot/nx-cloud-ce#87]
### Description

S3 is fine and largely adopted. But GCS and Azure Blob are also interesting alternatives and should be supported by `apps/server` as storage backend.

Update: Azure support is moved to dedicated issue #180

**Comment by jbadeau** [comment]
What about using minio to abstract the underlying storage

**Comment by clementguillot** [comment]
Minio is already in use in `docker compose` for local development of this project. At work, we use a managed S3-compatible backend but of course Minio is suitable for production environment.

I definitly should add a default Minio instance to Helm chart btw!
